config/routes.rb
Rails.application.routes.draw do
  root to: "home#landing"

  get '/companies', to: 'users#companies', as: 'companies'
  get '/company/:id', to: 'users#company', as: 'company'
  get '/social_companies', to: 'users#social_companies', as: 'social_companies'
  get '/social_company/:id', to: 'users#social_company', as: 'social_company'

  scope 'projects' do
    get '(/search/:search_text)', to: 'projects#index', as: 'projects'
    get ':id', to: 'projects#show', as: 'project'
  end

	scope 'profile' do
    resources :projects, except: [:index, :show]
    resources :benefits, path: 'offered-benefits', except: [:index, :show]

		get '/' , to: 'users#dashboard', as: 'profile'
	  get 'personal-info' , to: 'users#personal_info', as: 'personal_info'
	  get 'donations' , to: 'users#donations', as: 'donations'
	  get 'earned-benefits' , to: 'users#earned_benefits', as: 'earned_benefits'
	  get 'social-projects' , to: 'users#social_projects', as: 'social_projects'
		get 'find_sponsor/:project_id' , to: 'users#find_sponsor', as: 'find_sponsor'
    get 'offered-benefits' , to: 'users#offered_benefits', as: 'offered_benefits'

    scope 'donate' do
      post '/:id', to: 'donations#create', as: 'donate'
    end

    scope 'requirements' do
      get '/' , to: 'users#requirements', as: 'requirements'
      post '/', to: 'requirements#create', as:'require_sponsorship'
      post '/:id', to: 'requirements#destroy', as:'decline_sponsorship'
    end

    scope 'contracts' do
      get '/' , to: 'users#contracts', as: 'contracts'
      get 'new/(:id)', to: 'users#new_contract', as:'new_contract'
      post '/', to: 'contracts#create', as:'create_contract'
      post '/:id', to: 'contracts#destroy', as:'destroy_contract'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/benefit.rb
# frozen_string_literal: true

class Benefit < ApplicationRecord
  belongs_to :company, class_name: 'User', foreign_key: 'user_id'
  has_many :user_benefits
  has_many :donors, through: :user_benefits, source: :user, dependent: :destroy
  has_many :contracts, dependent: :destroy

  attr_reader :coupon_code

  def define_coupon_code(user:)
    @coupon_code = user_benefits.find_by(user_id: user.id).coupon_code
  end

  def to_s
    title
  end
end

app/controllers/benefits_controller.rb
# frozen_string_literal: true

class BenefitsController < ApplicationController
  load_and_authorize_resource
  before_action :set_profile_variables
  before_action :set_benefit, only: %i[show edit update destroy]

  # GET /benefits/1
  def show
  end

  # GET /benefits/new
  def new
    @benefit = Benefit.new
  end

  # GET /benefits/1/edit
  def edit
  end

  # POST /benefits
  def create
    @benefit = current_user.offered_benefits.new(benefit_params)

    if @benefit.save
      redirect_to :offered_benefits, flash: { success: t(:create,
                                                         scope: %i[flash benefit success]) }
    else
      render :new, flash: { error: t(:new, scope: %i[flash benefit error]) }
    end
  end

  # PATCH/PUT /benefits/1
  def update
    if @benefit.update(benefit_params)
      redirect_to :offered_benefits, flash: { success: t(:edit, scope: %i[flash benefit success]) }
    else
      render :edit, flash: { error: t(:edit, scope: %i[flash benefit error]) }
    end
  end

  # DELETE /benefits/1
  def destroy
    @benefit.destroy
    redirect_to :offered_benefits, flash: { success: t(:destroy, scope: %i[flash benefit success]) }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_benefit
    @benefit = Benefit.find_by(id: params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def benefit_params
    params.require(:benefit).permit(:title, :description)
  end
end

app/views/benefits/_form.html.erb
<%= form_with(model: benefit, local: true, url: (benefit.new_record? ? :offered_benefits : benefit_path(benefit))) do |form| %>
  <div class='form-group'>
    <%= form.label t(:title, scope: %i[benefit attributes]) %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group''>
    <%= form.label t(:description, scope: %i[benefit attributes]) %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <%= form.submit t(:submit), class: 'btn btn-primary' %>
<% end %>

app/views/benefits/edit.html.erb
<h2>
  <%= t(:title, scope: %i[benefit edit]) %>
  <%= link_to t(:back), :offered_benefits, class: 'btn btn-secondary btn-sm' %>
</h2>
<hr>
<%= render 'form', benefit: @benefit %>

app/views/benefits/index.html.erb
<h2>
Mis Beneficios
<%= link_to '<button type="button" class="btn btn-primary btn-sm">Agregar beneficio</button>'.html_safe, new_user_benefit_path %>
</h2>
<hr>
<% if @benefits.any? %>
  <% @benefits.each do |benefit| %>
  <div class="row py-2">
    <div class="col-10 card">
      <a href=<%= user_benefit_path(id: benefit.id) %> class="stretched-link"></a>
      <div class="card-body">
        <h5 class="card-title"><%= benefit.title %></h5>
        <p class="card-text"><%= benefit.description %></p>
      </div>
    </div>
    <div class="col-2">
      <div class="list-group">
        <%= link_to 'Editar', edit_user_benefit_path(@user.id, benefit.id), class: 'list-group-item list-group-item-action list-group-item-primary' %>
        <%= link_to 'Eliminar', user_benefit_path(@user.id, benefit.id), class: 'list-group-item list-group-item-action list-group-item-danger', method: :delete %>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
<div class="alert alert-info">
  <h5 class="alert-heading">
    No has agregado ningun beneficio aún.
  </h5>
  <hr>
  <div class="">
    Los beneficios que crees aparecerán aquí, donde podrás editarlos y eliminarlos
  </div>
</div>
<% end %>

<br>

app/views/benefits/new.html.erb
<h2>
  <%= t(:title, scope: %i[benefit new]) %>
  <%= link_to t(:back), :offered_benefits, class: 'btn btn-secondary btn-sm' %>
</h2>
<hr>
<%= render 'form', benefit: @benefit %>