config/routes.rb
Rails.application.routes.draw do
  root to: "home#landing"

  get '/companies', to: 'users#companies', as: 'companies'
  get '/company/:id', to: 'users#company', as: 'company'
  get '/social_companies', to: 'users#social_companies', as: 'social_companies'
  get '/social_company/:id', to: 'users#social_company', as: 'social_company'

  scope 'projects' do
    get '(/search/:search_text)', to: 'projects#index', as: 'projects'
    get ':id', to: 'projects#show', as: 'project'
  end

	scope 'profile' do
    resources :projects, except: [:index, :show]
    resources :benefits, path: 'offered-benefits', except: [:index, :show]

		get '/' , to: 'users#dashboard', as: 'profile'
	  get 'personal-info' , to: 'users#personal_info', as: 'personal_info'
	  get 'donations' , to: 'users#donations', as: 'donations'
	  get 'earned-benefits' , to: 'users#earned_benefits', as: 'earned_benefits'
	  get 'social-projects' , to: 'users#social_projects', as: 'social_projects'
		get 'find_sponsor/:project_id' , to: 'users#find_sponsor', as: 'find_sponsor'
    get 'offered-benefits' , to: 'users#offered_benefits', as: 'offered_benefits'

    scope 'donate' do
      post '/:id', to: 'donations#create', as: 'donate'
    end

    scope 'requirements' do
      get '/' , to: 'users#requirements', as: 'requirements'
      post '/', to: 'requirements#create', as:'require_sponsorship'
      post '/:id', to: 'requirements#destroy', as:'decline_sponsorship'
    end

    scope 'contracts' do
      get '/' , to: 'users#contracts', as: 'contracts'
      get 'new/(:id)', to: 'users#new_contract', as:'new_contract'
      post '/', to: 'contracts#create', as:'create_contract'
      post '/:id', to: 'contracts#destroy', as:'destroy_contract'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Donor and Company
  has_many :user_benefits
  has_many :earned_benefits, through: :user_benefits, source: :benefit

  # Company
  has_many :offered_benefits, class_name: 'Benefit'
  has_many :contracts, through: :offered_benefits
  has_many :sponsored_projects, through: :contracts, source: :project

  # SocialCompany
  has_many :projects

  # Company
  # (SocialCompany can get his pending requirements by looking through his proyects requirements)
  has_many :requirements

  # Donor and Company
  has_many :donations
  has_many :donated_projects, through: :donations, source: :project

  has_attached_file :avatar,
                    styles:      { medium: '300x300>', thumb: '100x100>' },
                    default_url: '/images/missing.jpg'
  has_attached_file :validation
  has_attached_file :compromise

  validates_attachment :avatar,
                       content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png'] },
                       size:         { in: 0..1000.kilobytes }
  validates_attachment :validation,
                       content_type: { content_type: ['application/pdf'] },
                       size:         { in: 0..2000.kilobytes }
  validates_attachment :compromise,
                       content_type: { content_type: ['application/pdf'] },
                       size:         { in: 0..2000.kilobytes }
  # validates_attachment_presence :validation, if: :require_validation_field
  # validates_attachment_presence :compromise, if: :require_compromise_field

  validates_presence_of :user_type
  validates_presence_of :name
  validates_presence_of :rut, if: :require_rut_field

  attr_reader :total_donations

  def calculate_donations
    @total_donations = donations.sum(&:amount)
    @total_donations += user_benefits.count * 2000 if user_type == 'Company'
  end

  def to_s
    name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  private

  def require_validation_field
    user_type.in?(%w[Company SocialCompany])
  end

  def require_compromise_field
    user_type.in?(%w[Company SocialCompany])
  end

  def require_rut_field
    user_type.in?(%w[Company SocialCompany])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_profile_variables, except: %i[
    companies
    company
    social_companies
    social_company
  ]

  before_action :set_ranking_variables, only: %i[
    companies
    company
    social_companies
    social_company
  ]

  def dashboard
    authorize! :dashboard, current_user
    @projects = current_user.projects
    @projects.map(&:calculate_donations)
    @donations = current_user.donations.reverse
    current_user.calculate_donations
    @given_benefits = current_user.offered_benefits
    @earned_benefits = current_user.earned_benefits
  end

  def personal_info
    authorize! :personal_info, current_user
  end

  def donations
    authorize! :donations, current_user
    @donations = current_user.donations.reverse
    current_user.calculate_donations
  end

  def earned_benefits
    authorize! :earned_benefits, current_user
    @benefits = current_user.earned_benefits
    @benefits.map { |b| b.define_coupon_code(user: current_user) }
  end

  def social_projects
    authorize! :social_projects, current_user
    @projects = current_user.projects
    @projects.map(&:calculate_donations)
  end

  def contracts
    authorize! :contracts, current_user
    @contracts = current_user.contracts
  end

  def new_contract
    authorize! :new_contract, current_user
    @contract = Contract.new
    @benefits = current_user.offered_benefits
    @selected = params[:id]
  end

  def offered_benefits
    authorize! :offered_benefits, current_user
    @benefits = current_user.offered_benefits
  end

  def find_sponsor
    authorize! :find_sponsor, current_user
    @companies = User.where(user_type: 'Company')
    @project = Project.find_by(id: params[:project_id])
  end

  def requirements
    authorize! :requirements, current_user
    req = current_user.requirements if company?
    req = current_user.projects.map(&:requirements).first if social_company?
    @requirements = req
  end

  # OUTSIDE /PROFILE, PUBLIC ACCESS

  def companies
    authorize! :companies, User
    @companies = User.where(user_type: 'Company')
  end

  def company
    authorize! :company, User
    @company = User.includes(:sponsored_projects).find_by(id: params[:id])
    @company.calculate_donations
  end

  def social_companies
    authorize! :companies, User
    @social_companies = User.where(user_type: 'SocialCompany')
  end

  def social_company
    authorize! :social_company, User
    @social_company = User.includes(:projects).find_by(id: params[:id])
    @social_company.projects.map(&:calculate_donations)
  end
end

app/views/users/companies.html.erb
<h2>
  <%= t(:many, scope: %i[company name]) %>
</h2>
<hr>
<div class="card-columns">
  <% @companies.each do |company| %>
    <div class="card" style="width: 13rem;">
      <a href=<%= company_path(company) %> class="stretched-link"></a>
      <%=image_tag company.avatar, class: 'card-img-top'%>
      <div class="card-body">
        <h5 class="card-title"><%= company %></h5>
        <p class="card-text"><%= company.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/company.html.erb
<%=image_tag @company.avatar, class: 'rounded mx-auto d-block mh-100', style:"height: 150px"%>
<h2 class="align-middle">
  <%= @company %>
  <%= link_to t(:back), :companies, class: 'btn btn-secondary btn-sm' %>
</h2>
<hr>
<div class="d-flex justify-content-around">
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:sponsored_projects) %></p>
    <h4 class="font-weight-bold text-info"><%= @company.sponsored_projects.count %></h4>
  </div>
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:estimated_total_donations) %></p>
    <h2 class="font-weight-bold text-primary"><%= currency_to_cl(@company.total_donations) %></h2>
  </div>
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:many, scope: %i[coupon name]) %> entregados</p>
    <h4 class="font-weight-bold text-info"><%= @company.user_benefits.count %></h4>
  </div>
</div>
<hr>
<div class="row mt-3">
  <div class="col">
    <h4>Acerca de la compañia</h4>
    <%= @company.description %>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <%= t(:many, scope: %i[benefit name])%> ofrecidos
      </div>
      <% if @company.offered_benefits.any? %>
        <table class="table">
          <tbody>
            <% @company.offered_benefits.each do |c|%>
            <tr>
              <td><%= fa_icon 'check'%></td>
              <td><%= c %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="card-body">
          <p>
            Esta empresa no ofrece ningún beneficio
            <%= fa_icon  'frown-o' %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="py-4">
  <h4 class="pb-2"><%= t(:many, scope: %i[project name])%> patrocinados</h4>
  <% if @company.sponsored_projects.any? %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th><%= t(:one, scope: %i[project name])%></th>
        <th><%= t(:one, scope: %i[social_company name])%> propietaria</th>
        <th># <%= t(:many, scope: %i[benefit name])%></th>
      </tr>
    </thead>
    <tbody>
      <% @company.sponsored_projects.each do |p|%>
      <tr>
        <td><%= link_to p, project_path(p) %></td>
        <td><%= link_to p.user, social_company_path(p.user) %></td>
        <td><%= link_to p.benefits.where(user_id: @company.id).count, project_path(p) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
  <div class="card-body">
    <p>
      Esta empresa no ofrece ningún beneficio
      <%= fa_icon  'frown-o' %>
    </p>
  </div>
  <% end %>
</div>

app/views/users/contracts.html.erb
<h2>Proyectos patrocinados</h2>
<hr>
<% if @contracts.any? %>
  <div class="list-group-item border bg-dark text-light font-weight-bold">
    <div class="row">
      <div class="col-5 m-auto text-center">
        <%= t(:one, scope: %i[project name])%>
      </div>
      <div class="col-5 m-auto text-center">
        <%= t(:many, scope: %i[benefit name]) %>
      </div>
      <div class="col">
      </div>
    </div>
  </div>
  <% @contracts.each do |c| %>
    <div class="list-group-item border">
      <div class="row">
        <div class="col-5 m-auto text-center">
          <%= link_to c.project, project_path(c.project)%>
        </div>
        <div class="col-5 m-auto text-center">
          <%= c.benefit %>
        </div>
        <div class="col m-auto text-center">
          <%= button_to t(:destroy), destroy_contract_path(c.id), class: 'btn btn-outline-danger' %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
<div class="alert alert-info">
  <h5 class="alert-heading">
    Aún no patrocinas proyectos
  </h5>
  <hr>
  <div class="">
    Una vez que asignes beneficios a proyectos sociales, podrás verlos aquí y comenzarás a ganar reconocimiento
  </div>
</div>
<% end %>

app/views/users/dashboard.html.erb
<% if social_company? %>
	<h2>Donaciones por día</h2>	
	<% if @projects.any? %>
		<% @projects.each do |project| %>
			<div class="graph">
				<h4><%= project.name %></h4>	
				<%= line_chart project.donations.group_by_day(:created_at).sum(:amount) %>
			</div>
		<% end %>	
	<% end %>
<% elsif company? %>
	<h2>Beneficios adquiridos por día</h2>
	<% if @given_benefits.any? %>
		<% @given_benefits.each do |benefit| %>
			<div class="graph">
				<h4><%= benefit.title %></h4>	
				<%= line_chart benefit.user_benefits.group_by_day(:created_at).count %>	
			</div>	
		<% end %>
	<% end %>
<% elsif donor? %>
	<div class="graph2">
		<h2>Dinero donado en cada proyecto</h2>	
		<%= pie_chart @donations.group_by{|d| d.project.name}.map{|p,d| [p, d.sum(&:amount)]} %>
	</div>	
<% end %>

app/views/users/donations.html.erb
<h2>Donaciones realizadas</h2>
<hr>
<% if @donations.any? %>
    <h4 class="text-right">
      Total:
      <span class="font-weight-bold"><%= currency_to_cl(current_user.total_donations) %></span>
    </h4>

  <div class="list-group-item border bg-dark text-light font-weight-bold">
    <div class="row">
      <div class="col-2 m-auto text-center">
        <%= t(:date)%>
      </div>
      <div class="col-8 m-auto text-center">
        <%= t(:one, scope: %i[project name]) %>
      </div>
      <div class="col m-auto text-center">
        <%= t(:amount) %>
      </div>
    </div>
  </div>
  <% @donations.each do |donation| %>
    <div class="list-group-item border">
      <div class="row">
        <div class="col-2 m-auto text-center">
          <%= get_date(donation.created_at) %>
        </div>
        <div class="col-8 m-auto text-center">
          <% if donation.project.present? %>
            <%= link_to donation.project.name, project_path(donation.project) %>
          <% else %>
            Projecto social eliminado
          <% end %>
        </div>
        <div class="col m-auto text-center">
          <%= currency_to_cl(donation.amount) %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
<div class="alert alert-info">
  <h5 class="alert-heading">
    Aún no haz realizado donaciones
  </h5>
  <hr>
  <div class="">
    Una vez que realices donaciones, podrás verlos aquí y comenzarás a ganar reconocimiento
  </div>
</div>
<% end %>

app/views/users/find_sponsor.html.erb
<h2>
  <%= t(:many, scope: %i[company name]) %>
  <%= link_to t(:back), :social_projects, class: "btn btn-secondary btn-sm" %>
</h2>
<hr>
<% @companies.each do |company| %>
  <div class="row list-group-item border">
    <div class="row" style="height: 60px">
      <div class="col-3 mh-100 test-light">
        <%=image_tag company.avatar, class: 'mw-100 mh-100'%>
      </div>
      <div class="col-5 m-auto text-center">
        <%= company %>
      </div>
      <div class="col m-auto text-center">
        <%= button_to t(:require), require_sponsorship_path(requirement: { user_id: company.id, project_id: @project.id }), class: 'btn btn-outline-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new_contract.html.erb
<h2>
  <%= t(:title, scope: %i[benefit new_contract]) %>
  <%= link_to t(:back), offered_benefits_path(current_user), class: 'btn btn-secondary btn-sm' %>
</h2>

<%= form_with(model: @contract, local: true, url: :create_contract) do |form| %>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <%= form.label t(:one, scope: %i[project name]), for:'selectProject' , class: "input-group-text"%>
  </div>
  <%= form.select :project_id, Project.all.collect{ |p| [p.name, p.id] }, { include_blank: 'Selecciona un proyecto', selected: @selected } , {class: 'custom-select'} %>
</div>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <%= form.label t(:one, scope: %i[benefit name]), for:'selectBenefit' , class: "input-group-text"%>
  </div>
  <%= form.select :benefit_id, @benefits.collect{ |p| [p.title, p.id] }, { include_blank: 'Selecciona un beneficio' } , {class: 'custom-select'} %>
</div>
<%= form.submit t(:submit), class: 'btn btn-primary' %>
<% end %>

app/views/users/offered_benefits.html.erb
<h2>
  <%= t(:title, scope: %i[benefit index]) %>
  <%= link_to t(:new, scope: %i[benefit index]), :new_benefit, class: "btn btn-primary btn-sm" %>
</h2>
<hr>
<% if @benefits.any? %>
  <% @benefits.each do |benefit| %>
  <div class="row py-2">
    <div class="col-10 card">
      <h4 class="card-header bg-transparent"><%= benefit %></h4>
      <div class="card-body">
        <p class="card-text"><%= benefit.description %></p>
      </div>
    </div>
    <div class="col-2">
      <div class="list-group">
        <%= link_to 'Editar', edit_benefit_path(benefit), class: 'list-group-item list-group-item-action list-group-item-primary' %>
        <%= link_to 'Eliminar', "/profile/offered-benefits/#{benefit.id}", class: 'list-group-item list-group-item-action list-group-item-danger', method: :delete %>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
<div class="alert alert-info">
  <h5 class="alert-heading">
    No has agregado ningun beneficio aún.
  </h5>
  <hr>
  <div class="">
    Los beneficios que crees aparecerán aquí, donde podrás editarlos y eliminarlos
  </div>
</div>
<% end %>

<br>

app/views/users/requirements.html.erb
<h2>Solicitudes de patrocinio</h2>
<hr>
<% if @requirements.any? %>
  <div class="list-group-item border bg-dark text-light font-weight-bold">
    <div class="row">
      <div class="col m-auto text-center">
        <%= t(:one, scope: %i[project name])%>
      </div>
      <% if social_company? %>
        <div class="col m-auto text-center">
          <%= t(:one, scope: %i[company name])%>
        </div>
      <% end %>
      <% if can? :create, Contract %>
        <div class="col-2 m-auto text-center">
        </div>
      <% end %>
      <div class="col-2 m-auto text-center">
      </div>
    </div>
  </div>
  <% @requirements.each do |r| %>
    <div class="list-group-item border">
      <div class="row">
        <div class="col m-auto text-center">
          <%= link_to r.project, project_path(r.project)%>
        </div>
        <% if social_company? %>
          <div class="col m-auto text-center">
            <%= r.user %>
          </div>
        <% end %>
        <% if can? :create, Contract %>
          <div class="col-2 m-auto text-center">
            <%= link_to t(:sponsor), new_contract_path(r.project.id), class: 'btn btn-outline-warning' %>
          </div>
        <% end %>
        <div class="col-2 m-auto text-center">
          <%= button_to t(:destroy), decline_sponsorship_path(r.id), class: 'btn btn-outline-danger' %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
<div class="alert alert-info">
  <h5 class="alert-heading">
    No hay nada nuevo por aquí
  </h5>
  <hr>
  <div class="">
    Las solicitudes de patrocinio por parte de los proyectos sociales aparecerán aquí
  </div>
</div>
<% end %>

app/views/users/social_companies.html.erb
<h2>
  <%= t(:many, scope: %i[social_company name]) %>
</h2>
<hr>
<div class="card-columns">
  <% @social_companies.each do |social_company| %>
    <div class="card" style="width: 13rem;">
      <a href=<%= social_company_path(social_company) %> class="stretched-link"></a>
      <%=image_tag social_company.avatar, class: 'card-img-top'%>
      <div class="card-body">
        <h5 class="card-title"><%= social_company %></h5>
        <p class="card-text"><%= social_company.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/social_company.html.erb
<%=image_tag @social_company.avatar, class: 'rounded mx-auto d-block mh-100', style:"height: 150px"%>
<h2>
  <%= @social_company %>
  <%= link_to t(:back), :social_companies, class: 'btn btn-secondary btn-sm' %>
</h2>
<hr>
<div class="d-flex justify-content-around">
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:many, scope: %i[project name]) %></p>
    <h2 class="font-weight-bold text-primary"><%= @social_company.projects.count %></h2>
  </div>
</div>
<hr>
<div class="">
  <h4>Acerca de la empresa social</h4>
  <%= @social_company.description %>
</div>

<div class="py-4">
  <h4 class="pb-2"><%= t(:many, scope: %i[project name])%></h4>
  <% if @social_company.projects.any? %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th><%= t(:one, scope: %i[project name])%></th>
        <th><%= t(:amount_collected)%></th>
        <th># <%= t(:many, scope: %i[donation name])%></th>
        <th># <%= t(:many, scope: %i[benefit name])%></th>
      </tr>
    </thead>
    <tbody>
      <% @social_company.projects.each do |p|%>
      <tr>
        <td><%= link_to p, project_path(p) %></td>
        <td><%= currency_to_cl(p.total_donations) %></td>
        <td><%= p.donations.count %></td>
        <td><%= link_to p.benefits.count, project_path(p) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
  <div class="card-body">
    <p>
      Esta empresa no tiene ningún proyecto
      <%= fa_icon  'frown-o' %>
    </p>
  </div>
  <% end %>
</div>

app/views/users/social_projects.html.erb
<h2>
  <%= t(:title, scope: %i[project index]) %>
  <%= link_to t(:new, scope: %i[project index]), new_project_path, class: "btn btn-primary btn-sm" %>
</h2>
<hr>
<% @projects.each do |project| %>
  <div class="row py-2">
    <div class="col-9 card">
      <a href=<%= project_path(project) %> class="stretched-link"></a>
      <h4 class="card-header bg-transparent text-primary"><%= project %></h4>
      <div class="d-flex justify-content-around text-center pt-2">
        <div class="">
          <p class="text-muted p-0 m-0"><%= t(:creation_date) %></p>
          <h5 class="font-weight-bold text-info"><%= get_date(project.created_at) %></h5>
        </div>
        <div class="">
          <p class="text-muted p-0 m-0"><%= t(:estimated_end_date, scope: %i[project attributes]) %></p>
          <h5 class="font-weight-bold text-info"><%= get_date(project.estimated_end_date) %></h5>
        </div>
      </div>
      <hr>
      <div class="row card-body">
        <div class="col">
          <div class="d-flex justify-content-around text-center">
            <div class="">
              <p class="text-muted p-0 m-0"><%= t(:amount_collected) %></p>
              <h4 class="font-weight-bold text-primary"><%= currency_to_cl(project.total_donations) %></h4>
            </div>
            <div class="">
              <p class="text-muted p-0 m-0"><%= t(:many, scope: %i[donation name]) %></p>
              <h4 class="font-weight-bold text-primary"><%= project.donations.count %></h4>
            </div>
          </div>
        </div>
        <% if project.benefits.any? %>
          <div class="col-6">
            <h5 class="card-text text-secondary"><%= t(:many, scope: %i[benefit name])%></h5>
            <table class="table table-borderless">
              <tbody>
                <% project.benefits.each do |b|%>
                <tr>
                  <td><%= b %></td>
                  <td style="width: 30%">(<%= b.company %>)</td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-3">
      <div class="list-group text-center">
        <%= link_to t(:require), find_sponsor_path(project_id: project.id), class: 'list-group-item list-group-item-action list-group-item-warning' %>
        <%= link_to t(:edit), edit_project_path(project), class: "list-group-item list-group-item-action list-group-item-primary" %>
        <%= link_to t(:destroy), "/profile/projects/#{project.id}", method: :delete, class: "list-group-item list-group-item-action list-group-item-danger" %>
      </div>
    </div>
  </div>
<% end %>