config/routes.rb
Rails.application.routes.draw do
  root to: "home#landing"

  get '/companies', to: 'users#companies', as: 'companies'
  get '/company/:id', to: 'users#company', as: 'company'
  get '/social_companies', to: 'users#social_companies', as: 'social_companies'
  get '/social_company/:id', to: 'users#social_company', as: 'social_company'

  scope 'projects' do
    get '(/search/:search_text)', to: 'projects#index', as: 'projects'
    get ':id', to: 'projects#show', as: 'project'
  end

	scope 'profile' do
    resources :projects, except: [:index, :show]
    resources :benefits, path: 'offered-benefits', except: [:index, :show]

		get '/' , to: 'users#dashboard', as: 'profile'
	  get 'personal-info' , to: 'users#personal_info', as: 'personal_info'
	  get 'donations' , to: 'users#donations', as: 'donations'
	  get 'earned-benefits' , to: 'users#earned_benefits', as: 'earned_benefits'
	  get 'social-projects' , to: 'users#social_projects', as: 'social_projects'
		get 'find_sponsor/:project_id' , to: 'users#find_sponsor', as: 'find_sponsor'
    get 'offered-benefits' , to: 'users#offered_benefits', as: 'offered_benefits'

    scope 'donate' do
      post '/:id', to: 'donations#create', as: 'donate'
    end

    scope 'requirements' do
      get '/' , to: 'users#requirements', as: 'requirements'
      post '/', to: 'requirements#create', as:'require_sponsorship'
      post '/:id', to: 'requirements#destroy', as:'decline_sponsorship'
    end

    scope 'contracts' do
      get '/' , to: 'users#contracts', as: 'contracts'
      get 'new/(:id)', to: 'users#new_contract', as:'new_contract'
      post '/', to: 'contracts#create', as:'create_contract'
      post '/:id', to: 'contracts#destroy', as:'destroy_contract'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user

  has_many :requirements, dependent: :destroy

  has_many :contracts, dependent: :destroy
  has_many :benefits, through: :contracts

  has_many :donations, dependent: :nullify
  has_many :donors, through: :donations, source: :user, dependent: :nullify

  validates_presence_of :user

  attr_reader :total_donations

  def calculate_donations
    @total_donations = donations.sum(&:amount)
  end

  def to_s
    name
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_profile_variables, except: %i[index show]
  before_action :set_ranking_variables, only: %i[index show]
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects
  def index
    @projects = if params[:search_text]
                  text = params[:search_text]
                  Project.select { |p| p.name.include?(text) || p.description.include?(text) }
                else
                  Project.all
                end
    @projects.map(&:calculate_donations)
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      flash[:success] = t(:create, scope: %i[flash project success], project: @project.name)
      redirect_to :social_projects
    else
      flash[:error] = t(:new, scope: %i[flash project error])
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      flash[:success] = t(:edit, scope: %i[flash project success], project: @project.name)
      redirect_to :social_projects
    else
      flash[:error] = t(:edit, scope: %i[flash project error])
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    flash[:success] = t(:destroy, scope: %i[flash project success], project: @project.name)
    redirect_to :social_projects
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find_by(id: params[:id])
    @project.calculate_donations
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :description, :estimated_end_date)
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, url: (project.new_record? ? '/profile/projects' : "/profile/projects/#{project.id}")) do |form| %>
  <div class='form-group'>
    <%= form.label t(:name, scope: %i[project attributes]) %>
    <%= form.text_field :name, class: 'form-control'%>
  </div>
  <div class='form-group'>
    <%= form.label t(:description, scope: %i[project attributes]) %>
    <%= form.text_area :description, class: 'form-control'%>
  </div>
  <div class='form-group'>
    <%= form.label t(:estimated_end_date, scope: %i[project attributes]) %>
    <%= form.date_field :estimated_end_date, class: 'form-control'%>
  </div>
  <%= form.submit t(:submit), class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<h2>
  <%= t(:title, scope: %i[project edit]) %>
  <%= link_to t(:back), projects_path, class: 'btn btn-secondary btn-sm' %>
</h2>
<hr>
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h2><%= t(:title, scope: %i[project index]) %></h2>
<hr>
<% @projects.each do |project| %>
  <div class="row py-2">
    <div class="col card">
      <a href=<%= project_path(project) %> class="stretched-link"></a>
      <h4 class="card-header bg-transparent text-primary"><%= project %></h4>
      <div class="row card-body">
        <div class="col">
          <p class="card-text"><%= project.description %></p>
        </div>
        <% if project.benefits.any? %>
          <div class="col-5">
            <h5 class="card-text text-secondary">Si donas, obtendras:</h5>
            <table class="table table-borderless">
              <tbody>
                <% project.benefits.first(2).each do |c|%>
                <tr>
                  <td><%= fa_icon 'check'%></td>
                  <td><%= c %></td>
                </tr>
                <% end %>
                <% if project.benefits.count > 2 %>
                <tr>
                  <td><%= fa_icon 'check'%></td>
                  <td class="font-weight-bold">Entre otros beneficios!</td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
      <div class="card-footer text-muted bg-transparent">
        <span class="float-right"><%= t(:owner, scope: %i[project show], social_company: project.user) %></span>
      </div>
    </div>
    <div class="col-2">
      <% if can? :create, Contract %>
        <%= link_to t(:sponsor), new_contract_path(project), class: 'btn btn-warning btn-block font-weight-bold' %>
      <% end %>
      <% unless social_company? %>
        <%= link_to t(:donate), donate_path(project.id), method: :post, class: 'btn btn-success btn-block font-weight-bold' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<h2>
  <%= t(:title, scope: %i[project new]) %>
  <%= link_to t(:back), :social_projects, class: 'btn btn-secondary btn-sm' %>
</h2>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h2>
  <%= t(:title, scope: %i[project show], project: @project.name)%>
  <%= link_to t(:back), projects_path, class: 'btn btn-secondary btn-sm' %>
</h2>
<hr>
<div class="d-flex justify-content-around">
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:creation_date) %></p>
    <h4 class="font-weight-bold text-info"><%= get_date(@project.created_at) %></h4>
  </div>
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:amount_collected) %></p>
    <h2 class="font-weight-bold text-primary"><%= currency_to_cl(@project.total_donations) %></h2>
  </div>
  <div class="text-center">
    <p class="text-muted p-0 m-0"><%= t(:estimated_end_date, scope: %i[project attributes]) %></p>
    <h4 class="font-weight-bold text-info"><%= get_date(@project.estimated_end_date) %></h4>
  </div>
</div>
<hr>
<div class="row mt-3">
  <div class="col">
    <h4>Acerca del proyecto</h4>
    <%= @project.description %>
  </div>
  <div class="col-5">
    <div class="py-2">
      <% if can? :create, Contract %>
      <%= link_to t(:sponsor), new_contract_path(@project), class: 'btn btn-lg btn-warning btn-block font-weight-bold' %>
      <% end %>
      <% unless social_company?%>
        <%= link_to t(:donate), donate_path(@project), method: :post, class: 'btn btn-lg btn-success btn-block font-weight-bold' %>
      <% end %>
    </div>
    <div class="card">
      <div class="card-header">
        <%= t(:many, scope: %i[benefit name]) %>
      </div>
      <% if @project.benefits.any? %>
        <table class="table table-hover">
          <tbody>
            <% @project.benefits.each do |b|%>
            <tr class="link" data-link="<%= company_path(b.company) %>">
              <td><%= fa_icon 'check'%></td>
              <td><%= b %></td>
              <td style="width: 30%">(<%= b.company %>)</td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="card-body">
          <p>
            Esta empresa no ofrece ningún beneficio
            <%= fa_icon  'frown-o' %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<hr>
<div class="text-right text-muted">
  <%= link_to t(:owner, scope: %i[project show], social_company: @project.user), social_company_path(@project.user)%>
</div>


<script>
  $("tr[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>